import { AppShell } from "../../components/app-shell";
import { Icon } from "../../components/icons";
import { analytics } from "../../lib/demo-data";
import { MetricCard, PageIntro, SectionTitle } from "../../components/ui";

export default function AnalyticsPage() {
  return <AppShell><PageIntro eyebrow="Measure the system" title="Analytics" description="Understand reliability, cost and human-review load across your automation fleet." /><div className="metric-grid analytics-metrics"><MetricCard label="Total runs" value="1,284" change="+14.2%" note="vs. last month" tone="blue" icon="activity" /><MetricCard label="Success rate" value="97.1%" change="+2.6%" note="last 30 days" tone="green" icon="check" /><MetricCard label="Avg. runtime" value="8.4s" change="−1.2s" note="faster than prior" tone="violet" icon="chart" /><MetricCard label="LLM spend" value="£42.18" change="£0.033 / run" note="last 30 days" tone="amber" icon="coin" /></div><div className="dashboard-grid analytics-grid"><section className="panel chart-panel"><SectionTitle title="Workflow volume" subtitle="Completed and waiting runs · last 7 days" /><div className="chart-wrap"><div className="chart-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="bar-chart">{analytics.map((item) => <div className="bar-column" key={item.label}><div className="bar-value" style={{ height: `${item.value}%` }}><span>{item.value}</span></div><small>{item.label}</small></div>)}</div></div></section><section className="panel cost-panel"><SectionTitle title="Cost by workflow" subtitle="Estimated LLM spend" /><div className="cost-list"><div><span className="cost-swatch blue" /><div><strong>Inbound Revenue Agent</strong><small>214 runs</small></div><b>$18.42</b></div><div><span className="cost-swatch violet" /><div><strong>AP Exception Agent</strong><small>86 runs</small></div><b>$13.28</b></div><div><span className="cost-swatch amber" /><div><strong>Support Escalation Agent</strong><small>42 runs</small></div><b>$10.48</b></div></div><div className="cost-total"><span>Total estimated spend</span><strong>$42.18</strong></div></section></div></AppShell>;
}

