import { AppShell } from "../../components/app-shell";
import { Icon } from "../../components/icons";
import { Button, PageIntro, SectionTitle, StatusPill } from "../../components/ui";

export default function SettingsPage() {
  return <AppShell><PageIntro eyebrow="Workspace controls" title="Settings" description="Manage policies, roles and the safeguards around your AI operations." action={<Button variant="secondary" icon="check">Saved</Button>} /><div className="settings-grid"><section className="panel settings-panel"><SectionTitle title="Safety policies" subtitle="Deterministic controls applied before a tool can run." /><SettingRow title="External actions" description="Require human approval before sending messages or posting externally." value="Always approve" icon="shield" /><SettingRow title="Maximum tool calls" description="Stop a run when it exceeds the per-workflow action budget." value="15 calls" icon="activity" /><SettingRow title="Maximum runtime" description="End a workflow that runs longer than the configured policy window." value="5 minutes" icon="refresh" /><SettingRow title="Replay policy" description="Allow operators to replay from the last durable checkpoint." value="Operators" icon="workflow" /></section><section className="panel settings-panel"><SectionTitle title="Team access" subtitle="Northstar Demo · 4 members" /><div className="team-row"><div className="team-avatar">H</div><div><strong>Henry</strong><span>henry · owner</span></div><StatusPill status="Owner" /></div><div className="team-row"><div className="team-avatar purple">A</div><div><strong>Alex Operator</strong><span>alex · operator</span></div><StatusPill status="Operator" /></div><div className="team-row"><div className="team-avatar amber">V</div><div><strong>Finance Viewer</strong><span>finance · viewer</span></div><StatusPill status="Viewer" /></div><button className="invite-button"><Icon name="plus" size={15} /> Invite teammate</button></section></div><section className="panel audit-settings"><SectionTitle title="Audit and data" subtitle="Retention and environment boundaries" /><div className="audit-grid"><div><span>Environment</span><strong><i className="live-dot" /> Local sandbox</strong></div><div><span>Trace retention</span><strong>90 days</strong></div><div><span>Credential storage</span><strong>Encrypted server-side</strong></div><div><span>Last policy update</span><strong>Today · 08:41</strong></div></div></section></AppShell>;
}

function SettingRow({ title, description, value, icon }: { title: string; description: string; value: string; icon: Parameters<typeof Icon>[0]["name"] }) {
  return <div className="setting-row"><div className="setting-icon"><Icon name={icon} size={17} /></div><div className="setting-copy"><strong>{title}</strong><span>{description}</span></div><span className="setting-value">{value}<Icon name="chevron" size={14} /></span></div>;
}

